plugins: 
  - jekyll-redirect-from
  - jekyll-sitemap
 
metadata:   
  pagetitle: "ExB Plasmas Workshop 2022"
  pagesubtitle: "Madrid, online event"
  pagedescription: "Website of the ExB Plasmas Workshop 2022"
  pagekeywords: "electric propulsion, plasma thrusters, hall effect thrusters, magnetic nozzles, helicon thrusters, space debris, plasma physics, numerical simulation, equipo de propulsion espacial y plasmas"
  authorname: "Mario Merino"    

assets: 
  avatar: "assets/images/ExBworkshop.png"
  icon: "assets/images/icon.png"
 
nav:  
  - title: "Information"
    id: "information-link"
    url: "#information"
    icon: "fa-calendar-o"    
  - title: "Topical sessions"
    id: "sessions-link"
    url: "#sessions"
    icon: "fa-book"	
  - title: "Poster session"
    id: "posters-link"
    url: "#posters"
    icon: "fa-pie-chart"	
  - title: "Discussion"
    id: "discussion-link"
    url: "#discussion"
    icon: "fa-bullhorn"	    
  - title: "Contact"
    id: "contact-link"
    url: "#contact"
    icon: "fa-envelope"
